version: '3.2'
services:
  # PROXY
  nginx:
    image: nginx:1.19-alpine
    volumes:
      - ./nginx/certs:/etc/ssl/certs
      - ./nginx/templates:/etc/nginx/templates/
      - ./nginx/snippets:/etc/nginx/snippets
    env_file:
      - nginx.env
    ports:
      - ${NGINX_EXTERNAL_PORT}:443
    restart: unless-stopped

  # DATABASE
  mongo:
    image: mongo:4.2
    ports:
      - ${MONGO_EXTERNAL_PORT}:27017
    env_file:
      - mongo.env
    command: --quiet
    restart: unless-stopped
    volumes:
     - ./mongo/mongo-data:/data/db
     - ./mongo/mongo-configdb:/data/configdb
     - ./mongo/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro

  # DATABASE WEB
  mongo_express:
    image: mongo-express
    volumes:
      - ./mongo_express:/data
    ports:
      - ${MONGO_EXPRESS_EXTERNAL_PORT}:8081
    env_file:
      - mongo_express.env
    depends_on:
      - mongo

  # API
  api:
    image: rabadandotdev/trans-med-api-ptin
    ports:
      - ${API_EXTERNAL_PORT}:5000
    env_file:
      - api.env
    depends_on:
      - mongo

  # WEB BACKEND
  nextjs:
    image: rabadandotdev/trans-med-web-ptin
    ports:
      - ${NEXTJS_EXTERNAL_PORT}:3000
    env_file:
      - nextjs.env
    depends_on:
      - api
    restart: unless-stopped

  # MQTT SERVER
  mosquitto:
    image: eclipse-mosquitto:latest
    volumes:
      - ./mosquitto:/mosquitto/
    env_file:
      - mosquitto.env
    ports:
      - ${MOSQUITTO_EXTERNAL_PORT}:1883
      - ${MOSQUITTO_EXTERNAL_PORT_SECURE}:8883
    restart: always

  # MQTT WATCHDOG
  mqtt-subscriber:
    image: rabadandotdev/trans-med-mqttsub-ptin
    env_file:
      - mqtt-subscriber.env
    depends_on:
      - mosquitto
    ports:
    - ${MQTT_SUBSCRIBER_EXTERNAL_PORT}:4000
